import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import ts from 'typescript';
const js=ts.transpileModule(readFileSync(new URL('../lib/game/engine.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {beginRound,advance,publicRoom}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function room(n=3){return {code:'ABC234',host:'p0',players:Array.from({length:n},(_,i)=>({id:'p'+i,tokenHash:'secret'+i,name:'Player '+i,score:0,fooled:0,correct:0})),phase:'lobby',round:0,total:6,deadline:0,generation:'',ai:'',aiError:'',question:'',answers:{},votes:{},options:[],history:[],used:[],deltas:{},created:0,mode:'cantonese'};}
test('10-player round, anonymous voting, scoring and one-time settlement',()=>{const r=room(10);beginRound(r,100);r.ai='AI answer';for(const p of r.players)r.answers[p.id]='answer '+p.id;assert(advance(r,200));assert.equal(r.options.length,11);const view=publicRoom(r,'p0',1);assert(!JSON.stringify(view).includes('tokenHash'));assert(!JSON.stringify(view).includes('secret'));assert(view.options.every(o=>!('author'in o)&&!('voters'in o)));const ai=r.options.find(o=>o.author==='AI');const human=r.options.find(o=>o.author==='p1');r.votes=Object.fromEntries(r.players.map((p,i)=>[p.id,i===0?human.id:ai.id]));advance(r,300);assert.equal(r.players[0].score,0);assert.equal(r.players[1].score,3);assert.equal(r.players[2].score,2);assert.equal(r.players[1].fooled,1);const scores=r.players.map(p=>p.score);assert.equal(advance(r,301),false);assert.deepEqual(r.players.map(p=>p.score),scores);assert(publicRoom(r,'p0',2).options.every(o=>'author'in o));});
test('no AI fallback pretending to be a model, no score on failed round',()=>{const r=room();beginRound(r,0);r.answers={p0:'one',p1:'two'};advance(r,30001);assert.equal(r.phase,'reveal');assert(r.aiError);assert.equal(r.options.length,0);assert(r.players.every(p=>p.score===0));});
test('late responders do not block transitions and a full game ends',()=>{const r=room();let now=100;for(let i=0;i<6;i++){if(!i)beginRound(r,now);assert.equal(r.round,i+1);r.ai='a';r.answers={p0:'x',p1:'y'};advance(r,r.deadline+1);assert.equal(r.phase,'voting');advance(r,r.deadline+1);assert.equal(r.phase,'reveal');now=r.deadline+1;advance(r,now);}assert.equal(r.phase,'finished');assert.equal(new Set(r.used).size,6);});
test('writing state does not leak other answers or the model answer',()=>{const r=room();beginRound(r,0);r.ai='hidden AI';r.answers={p0:'mine',p1:'hidden human'};const v=publicRoom(r,'p0',1);assert.equal(v.myAnswer,'mine');assert.equal(v.options.length,0);assert(!JSON.stringify(v).includes('hidden'));});
