'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,Copy,Users,Volume2,VolumeX,LogOut,LoaderCircle,Crown,ScanFace,RotateCcw,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import type {publicRoom} from '@/lib/game/engine';
type State=ReturnType<typeof publicRoom>&{me:string};
type Session={code:string;token:string};
const phases={lobby:'等齊人，開波。',writing:'亂作一句，扮到似。',voting:'邊一句係 AI？',reveal:'估唔到，係你。',finished:'今場，邊個最識呃？'};
const avatars=['#ddff00','#b9a4ff','#ffad79','#85ded5','#ff91b5','#a9c8ff','#f3cc60','#9ada9b','#c7bba8','#c2cae0'];
function getToken(){let token=localStorage.getItem('realai.token');if(!token){token=crypto.randomUUID()+crypto.randomUUID().replace(/-/g,'');localStorage.setItem('realai.token',token);}return token;}
export default function Home(){
 const [room,setRoom]=useState<State|null>(null),[session,setSession]=useState<Session|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[tab,setTab]=useState('create'),[mode,setMode]=useState('cantonese'),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sound,setSound]=useState(false),[time,setTime]=useState(Date.now()),[offset,setOffset]=useState(0),[restoring,setRestoring]=useState(true),[pin,setPin]=useState('');
 const roomRef=useRef<State|null>(null),audioRef=useRef<AudioContext|null>(null),lastBeep=useRef('');
 const apply=(r:State)=>{if(roomRef.current&&roomRef.current.code===r.code&&roomRef.current.version>r.version)return;roomRef.current=r;setRoom(r);setOffset(r.serverTime-Date.now());setError('');};
 async function request(payload:Record<string,unknown>,s?:Session|null):Promise<State>{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(s?.token||getToken())},body:JSON.stringify({...payload,...(s?{code:s.code}:{})}),signal:AbortSignal.timeout(25000)});const data=await res.json() as State & {error?:string};if(!res.ok)throw Object.assign(new Error(data.error||'連線失敗，請再試。'),{status:res.status});return data;}
 useEffect(()=>{let cancelled=false;setName(localStorage.getItem('realai.name')||'');const invited=new URLSearchParams(location.search).get('room');if(invited){setCode(invited.toUpperCase());setTab('join');}const saved=localStorage.getItem('realai.session');if(saved){try{const s=JSON.parse(saved) as Session;if(invited&&invited.toUpperCase()!==s.code){setRestoring(false);return;}request({action:'sync'},s).then(r=>{if(!cancelled){apply(r);setSession(s);}}).catch((e)=>{if(!cancelled){setError(e.message);if(e.status===401||e.status===404)localStorage.removeItem('realai.session');}}).finally(()=>{if(!cancelled)setRestoring(false);});}catch{localStorage.removeItem('realai.session');setRestoring(false);}}else setRestoring(false);return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!session)return;let ended=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await request({action:'sync'},session);if(!ended)apply(r);}catch(e){if(!ended)setError(e instanceof Error?e.message:'連線中斷，正在重連…');}finally{if(!ended)timer=setTimeout(poll,document.hidden?6000:1800);}};timer=setTimeout(poll,500);return()=>{ended=true;clearTimeout(timer);};},[session]);
 useEffect(()=>{const timer=setInterval(()=>setTime(Date.now()),200);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!room)return;const k=`realai.draft:${room.code}:${room.round}`;setDraft(sessionStorage.getItem(k)||'');},[room?.round,room?.code]);
 const seconds=room?Math.max(0,Math.ceil((room.deadline-time-offset)/1000)):0;
 useEffect(()=>{if(!room||!sound||!['writing','voting'].includes(room.phase)||seconds<1||seconds>5)return;const key=`${room.round}:${room.phase}:${seconds}`;if(lastBeep.current===key)return;lastBeep.current=key;const ctx=audioRef.current;if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=seconds===1?880:550;gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);osc.start();osc.stop(ctx.currentTime+.12);navigator.vibrate?.(30);},[seconds,sound,room?.phase,room?.round]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_party_state',description:'Read the current visible party room, phase, scores and anonymous options; no secret answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>roomRef.current?{code:roomRef.current.code,phase:roomRef.current.phase,round:roomRef.current.round,players:roomRef.current.players,options:roomRef.current.options}:{phase:'home'}},{signal:abort.signal})).catch(()=>{});}catch{}return()=>abort.abort();},[]);
 async function enter(){if(busy)return;setBusy(true);setError('');try{const r=await request({action:tab,name,code:code.toUpperCase(),mode,pin});const s={code:r.code,token:getToken()};localStorage.setItem('realai.session',JSON.stringify(s));localStorage.setItem('realai.name',name);setSession(s);apply(r);history.replaceState(null,'','?room='+r.code);}catch(e){setError(e instanceof Error?e.message:'無法加入');}finally{setBusy(false);}}
 async function action(action:string,extra:Record<string,unknown>={}){if(busy||!session)return;setBusy(true);try{const r=await request({action,round:room?.round,...extra},session);if(action==='leave'){exit();return;}if(action==='reset'){for(let i=0;i<=6;i++)sessionStorage.removeItem(`realai.draft:${r.code}:${i}`);}apply(r);}catch(e){toast.error(e instanceof Error?e.message:'請再試一次');}finally{setBusy(false);}}
 function exit(){if(room){setCode(room.code);setTab('join');}setSession(null);setRoom(null);roomRef.current=null;localStorage.removeItem('realai.session');history.replaceState(null,'',location.pathname);setError('');}
 function toggleSound(){if(!sound){const C=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(C){audioRef.current ||= new C();void audioRef.current.resume();}}setSound(!sound);}
 async function copy(){try{await navigator.clipboard.writeText(location.origin+'/?room='+room!.code);toast.success('邀請連結已複製');}catch{toast.info('房間碼：'+room!.code);}}
 const host=room?.host===room?.me,me=room?.players.find(p=>p.id===room.me),ranking=room?[...room.players].sort((a,b)=>b.score-a.score):[];
 return <div className="app-shell"><Toaster position="top-center" richColors/><header className="topbar"><a href="/" className="brand" aria-label="人還是 AI 首頁"><span className="brand-mark">?</span><span>REAL<span className="brand-slash">/</span>AI</span></a><div className="top-actions">{room&&<span className="room-label">ROOM <b>{room.code}</b></span>}<Button variant="ghost" size="icon" onClick={toggleSound} aria-label={sound?'關閉音效':'開啟音效'}>{sound?<Volume2/>:<VolumeX/>}</Button></div></header>
 {!room?<main className="home"><section className="intro"><div className="eyebrow"><span className="tag">PARTY GAME 01</span><span>3–10 人 · 每局約 6 分鐘</span></div><h1>人還是<br/><span className="acid">AI</span><span className="question-mark">?</span></h1><p className="intro-line">你朋友，可能比 AI 更似 AI。</p><div className="mini-rules"><div><b>01</b><span>一起亂作答案</span></div><div><b>02</b><span>投票揪出 AI</span></div><div><b>03</b><span>揭曉誰呃到誰</span></div></div><div className="score-note"><span>捉到 AI <b>+2</b></span><span>呃到一個朋友 <b>+1</b></span></div></section><section className="entry-panel"><div className="panel-heading"><ScanFace size={25}/><span>真人請入座</span><span className="tiny-index">[ 01–10 ]</span></div><Tabs value={tab} onValueChange={setTab}><TabsList className="entry-tabs"><TabsTrigger value="create">開個房間</TabsTrigger><TabsTrigger value="join">加入朋友</TabsTrigger></TabsList></Tabs><form onSubmit={e=>{e.preventDefault();void enter();}}><label htmlFor="name">你的暱稱</label><Input id="name" autoComplete="nickname" maxLength={12} placeholder="今晚用咩名？" value={name} onChange={e=>setName(e.target.value)} required/>{tab==='join'?<><label htmlFor="code">6 位房間碼</label><Input id="code" className="code-input" autoCapitalize="characters" autoComplete="off" maxLength={6} placeholder="ABC234" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} required/></>:<><label htmlFor="mode">AI 用甚麼語氣？</label><select id="mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="cantonese">廣東話 · 熟口熟面</option><option value="chinese">中文 · 日常口語</option></select><details className="pin-details"><summary>房主設有開房密碼？</summary><Input aria-label="開房密碼" type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="只在房主有設定時需要"/></details></>}{error&&<p className="error" role="alert">{error}</p>}<Button className="primary-button" disabled={busy||restoring||!name.trim()||(tab==='join'&&code.length!==6)} type="submit">{busy||restoring?<><LoaderCircle className="spin"/>正在連線</>:<>{tab==='create'?'建立房間':'即刻入場'}<ArrowUpRight/></>}</Button></form><p className="entry-foot">毋須註冊。叫朋友各自用手機入場就玩得。</p></section><p className="privacy-note">為了讓 AI 學習這局的語氣，最近幾輪的匿名答案會傳送至 SiliconFlow。請勿填寫私人資料。</p></main>:<main className="game"><div className="game-heading"><div><p className="eyebrow">{room.phase==='lobby'?'THE WAITING ROOM':room.phase==='finished'?'FINAL RESULTS':`ROUND ${String(room.round).padStart(2,'0')} / ${String(room.total).padStart(2,'0')}`}</p><h1>{phases[room.phase]}</h1></div>{!['lobby','finished'].includes(room.phase)&&<div className={'countdown '+(seconds<=5?'urgent':'')} aria-label={`剩餘 ${seconds} 秒`}><b>{String(seconds).padStart(2,'0')}</b><span>SEC</span></div>}</div>{error&&<div className="connection-error" role="alert">{error}<Button variant="ghost" onClick={exit}>回到入場頁</Button></div>}
 <div className="game-layout"><section className="play-surface">
 {room.phase==='lobby'&&<><div className="invite-box"><span>叫朋友輸入房間碼</span><strong>{room.code}</strong><Button className="soft-button" onClick={copy}><Copy size={16}/>複製邀請連結</Button></div><div className="lobby-rules"><h2>30 秒就識玩</h2><p>每輪 30 秒寫一句答案，AI 也會寫。答案混在一起，你要揪出 AI。</p><div className="scoring"><span>揀中 AI <b>+2 分</b></span><span>有人誤認你是 AI <b>+1 分 / 人</b></span></div><p className="muted">共 6 輪 · 不能投自己 · 超時仍可繼續下一階段</p></div><Button className="primary-button" disabled={!host||room.players.length<3||busy} onClick={()=>action('start')}>{busy?<LoaderCircle className="spin"/>:host?room.players.length<3?`再等 ${3-room.players.length} 位朋友`:'人齊，開始！':'等房主開始'}{!busy&&<ArrowUpRight/>}</Button></>}
 {room.phase==='writing'&&<><div className="phase-label"><span className="tag">作答時間</span><span>{room.players.filter(p=>p.answered).length}/{room.players.length} 已交答案</span></div><h2 className="prompt">{room.question}</h2><p className="muted">認真亂講也可以。目標：令朋友以為你是 AI。</p>{room.myAnswer?<div className="submitted"><Check/><b>收到了，等其他人。</b><p>「{room.myAnswer}」</p><span>答案已鎖定，留意下一輪投票。</span></div>:<form onSubmit={e=>{e.preventDefault();void action('answer',{answer:draft});}}><Textarea aria-label="你的答案" placeholder="用一句話，混淆全場…" maxLength={60} value={draft} disabled={seconds===0} onChange={e=>{setDraft(e.target.value);sessionStorage.setItem(`realai.draft:${room.code}:${room.round}`,e.target.value);}}/><div className="answer-foot"><span>{Array.from(draft).length}/60 字</span><span>提交後不能修改</span></div><Button type="submit" className="primary-button" disabled={busy||!draft.trim()||seconds===0}>{seconds===0?'時間到，正在收答案':busy?'提交中…':'交答案'}<ArrowUpRight/></Button></form>}</>}
 {(room.phase==='voting'||room.phase==='reveal')&&<><div className="phase-label"><span className="tag">{room.phase==='voting'?'找出唯一 AI':'身份揭曉'}</span><span>{room.phase==='voting'?`${room.players.filter(p=>p.voted).length}/${room.players.length} 已投票`:`本輪 ${me?(room.deltas[me.id]||0):0} 分`}</span></div><h2 className="vote-prompt">{room.question}</h2>{room.notice&&<p className="error">{room.notice}</p>}<div className="answers-grid">{room.options.map((o,i)=>{const author='author'in o?o.author:undefined;const voters='voters'in o?(o.voters as string[]):[];const ai=author==='AI';return <button key={o.id} className={'answer-card '+(room.myVote===o.id?'selected ':'')+(ai?'is-ai ':'')+(o.mine?'mine':'')} disabled={room.phase!=='voting'||!!room.myVote||o.mine||busy||seconds===0} onClick={()=>action('vote',{option:o.id})}><div className="card-top"><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{room.phase==='reveal'?(ai?'AI':room.players.find(p=>p.id===author)?.name||'玩家'):o.mine?'你的答案':room.myVote===o.id?'你投了這句':''}</span>{(ai||room.myVote===o.id)&&<Check size={18}/>}</div><p>{o.text}</p>{room.phase==='reveal'&&<div className="voters">{voters.length?`${voters.map(id=>room.players.find(p=>p.id===id)?.name).join('、')} ${ai?'捉到了':'中招'}`:'沒有人投這句'}</div>}</button>})}</div>{room.phase==='voting'&&<p className="vote-hint">{room.myVote?'投票已鎖定。可以開始懷疑身邊的人了。':'點一下投票，提交後不能更改。'}</p>}{room.phase==='reveal'&&<p className="vote-hint">{seconds>0?`${seconds} 秒後${room.round===room.total?'公佈總排名':'進入下一輪'}`:'正在同步下一階段…'}</p>}</>}
 {room.phase==='finished'&&<><div className="winner-block"><span className="tag">{ranking.filter(p=>p.score===ranking[0]?.score).length>1?'並列第一':'本場第一'}</span><h2>{ranking.filter(p=>p.score===ranking[0]?.score).map(p=>p.name).join('、')}</h2><div className="winner-score">{ranking[0]?.score||0}<span>分</span></div></div><div className="final-stats"><div><b>{me?.correct||0}</b><span>次捉到 AI</span></div><div><b>{me?.fooled||0}</b><span>次呃到朋友</span></div></div><Button className="primary-button" disabled={!host||busy} onClick={()=>action('reset')}><RotateCcw/>{host?'再嚟一局':'等房主再開一局'}</Button></>}
 </section><aside className="players-panel"><div className="players-title"><h2>{room.phase==='finished'?'最終排名':'在場玩家'}</h2><span><Users size={15}/>{room.players.length}/10</span></div><div className="player-list">{(room.phase==='lobby'?room.players:ranking).map((p,i)=><div className={'player-row '+(p.id===room.me?'self':'')} key={p.id}><div className="avatar" style={{background:avatars[room.players.findIndex(x=>x.id===p.id)%10]}}>{room.phase==='finished'?i+1:Array.from(p.name)[0]}</div><div className="player-name"><b>{p.name}{p.id===room.me&&<small>你</small>}</b><span>{p.id===room.host?<><Crown size={12}/>房主</>:room.phase==='writing'?(p.answered?'已交答案':'思考中…'):room.phase==='voting'?(p.voted?'已投票':'觀察中…'):'玩家'}</span></div>{host&&room.phase==='lobby'&&p.id!==room.me?<Button variant="ghost" size="icon" aria-label={`移除 ${p.name}`} onClick={()=>action('kick',{player:p.id})}><X size={15}/></Button>:<div className="player-score">{p.score}{room.phase==='reveal'&&!!room.deltas[p.id]&&<small>+{room.deltas[p.id]}</small>}</div>}</div>)}</div>{!['lobby','finished'].includes(room.phase)&&<div className="round-progress"><span>第 {room.round} / {room.total} 輪</span><Progress value={room.round/room.total*100}/></div>}<Button variant="ghost" className="leave-button" onClick={()=>['lobby','finished'].includes(room.phase)?action('leave'):exit()}><LogOut size={15}/>{['lobby','finished'].includes(room.phase)?'離開房間':'暫離畫面'}</Button></aside></div></main>}
 <footer><span>REAL / AI</span><span>信直覺。唔好太信朋友。</span><span>BY XIOSHON</span></footer></div>;
}
